### ISSUE TITLE
What is the DOCKER_TAG variable advantage?

### ISSUE THREAD

**Issue by pierreabreup** [michzimny/learninglocker2-docker#5]
I'm asking it because in docker-compose.yml I could create the image this way:
```
    api:
        build:
          context: ./app/
        environment:
            - DOMAIN_NAME
            - APP_SECRET
            - SMTP_HOST
            - SMTP_PORT
            - SMTP_SECURED
            - SMTP_USER
            - SMTP_PASS
        command: "node api/dist/server"
        restart: unless-stopped
        depends_on:
            - mongo
            - redis
        volumes:
            - "${DATA_LOCATION}/app-storage:/opt/learninglocker/storage"
```

Best
